version: "3.8"

services:
  rest-api-prd:
    container_name: rest-api-prd
    env_file: .env
    build:
      target: production
      context: .
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"

  rest-api-dev:
    container_name: rest-api-dev
    restart: unless-stopped
    env_file: .env
    build:
      target: dev
      context: .
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
      - 9229:9229
    volumes:
      - .:/project
      - node_modules:/project/node_modules/
volumes:
  node_modules:
